blueprint:
  name: ZHA - IKEA Styrbar - Warm White Spectrum
  description: Control a light with white spectrum
    Remote connected trough ZHA
  domain: automation
  input:
    remote:
      name: IKEA Styrbar remote control
      description: Select the remote control you wish to use.
      selector:
        device:
          integration: zha
          manufacturer: IKEA of Sweden
          model: Remote Control N2
          multiple: false
    light:
      name: Light
      description: Select the light entity you wish to control.
      selector:
        entity:
          domain:
          - light
          multiple: false
    color_temp_step:
      name: Color Temp Step
      description: Kelvin at which color temperature goes up and down on button hold
      default: 100
      selector:
        number:
          min: 0
          max: 1000
          unit_of_measurement: "kelvin"
    color_temp_step_press:
      name: Color Temp Step On Press
      description: Kelvin at which color temperature goes up and down on button press
      default: 500
      selector:
        number:
          min: 0
          max: 1000
          unit_of_measurement: "kelvin"
    min_color_temp:
      name: Minimum Color Value
      description: Minimum device supported color temperature in Kelvin
      default: 2202
      selector:
        number:
          min: 2000
          max: 6500
          unit_of_measurement: "kelvin"
    max_color_temp:
      name: Maximum Color Value
      description: Maximum device supported color temperature in Kelvin
      default: 4000
      selector:
        number:
          min: 2000
          max: 6500
          unit_of_measurement: "kelvin"
    transition_time:
      name: Transition time
      description: Time in seconds in which transitions happen 
      default: 0.5
      selector:
        number:
          min: 0.0
          max: 5.0
          step: 0.1
          unit_of_measurement: seconds
  source_url: https://community.home-assistant.io/t/zha-ikea-styrbar-warm-white-lights/341688
mode: restart
max_exceeded: silent
variables:
  var_light: !input light
  var_color_temp_step: !input color_temp_step
  var_color_temp_step_press: !input color_temp_step_press
  var_min_color_temp: !input min_color_temp
  var_max_color_temp: !input max_color_temp
  var_transition_time: !input transition_time
trigger:
- platform: event
  event_type: zha_event
  event_data:
    device_id: !input remote
action:
- choose:
  - conditions:
    - condition: template
      value_template: '{{ trigger.event.data.command == "press" }}'
    - condition: template
      value_template: '{{ trigger.event.data.args == [256,13,0] }}'
    sequence:
    - service: light.turn_on
      target:
        entity_id: !input light
      data:
        color_temp_kelvin: '{{ max(state_attr(var_light, "color_temp_kelvin") - var_color_temp_step_press, var_min_color_temp) }}'
        transition: !input transition_time
  - conditions:
    - condition: template
      value_template: '{{ trigger.event.data.command == "hold" }}'
    - condition: template
      value_template: '{{ trigger.event.data.args == [3328,0] }}'
    sequence:
    - repeat:
        while: []
        sequence:
        - service: light.turn_on
          target:
            entity_id: !input light
          data:
            color_temp_kelvin: '{{ max(state_attr(var_light, "color_temp_kelvin") - var_color_temp_step, var_min_color_temp) }}'
            transition: !input transition_time
        - delay:
            milliseconds: "{{ var_transition_time * 1000 }}"
  - conditions:
    - condition: template
      value_template: '{{ trigger.event.data.command == "press" }}'
    - condition: template
      value_template: '{{ trigger.event.data.args == [257,13,0] }}'
    sequence:
    - service: light.turn_on
      target:
        entity_id: !input light
      data:
        color_temp_kelvin: '{{ min(state_attr(var_light, "color_temp_kelvin") + var_color_temp_step_press, var_max_color_temp) }}'
        transition: !input transition_time
  - conditions:
    - condition: template
      value_template: '{{ trigger.event.data.command == "hold" }}'
    - condition: template
      value_template: '{{ trigger.event.data.args == [3329,0] }}'
    sequence:
    - repeat:
        while: []
        sequence:
        - service: light.turn_on
          target:
            entity_id: !input light
          data:
            color_temp_kelvin: '{{ min(state_attr(var_light, "color_temp_kelvin") + var_color_temp_step, var_max_color_temp) }}'
            transition: !input transition_time
        - delay:
            milliseconds: "{{ var_transition_time * 1000 }}"
  default: []
